# Generated by Django 4.1.7 on 2023-03-23 13:25

from django.db import migrations
import markdownfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_alter_project_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=markdownfield.models.MarkdownField(rendered_field='text_rendered', use_editor=False),
        ),
    ]
