# Generated by Django 4.1.7 on 2023-03-23 13:33

from django.db import migrations
import markdownfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_alter_project_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=markdownfield.models.MarkdownField(rendered_field='text_rendered'),
        ),
    ]
